In [4]:
import sys
from pathlib import Path

from src.data.build_clean_df import build_divvy_datasets
from src.features.feature_engineering import add_time_and_lag_features

In [6]:
ROOT = Path.cwd().parents[0]

DATA_RAW = ROOT / "data" / "raw"
DATA_PROCESSED = ROOT / "data" / "processed"
DATA_PROCESSED.mkdir(parents=True, exist_ok=True)

# 1) Build demand dataset (hourly + weather)
demand = build_divvy_datasets(
    trip_paths=[
        DATA_RAW / "Divvy_Trips_2017_Q1.csv",
        DATA_RAW / "Divvy_Trips_2017_Q2.csv",
        DATA_RAW / "Divvy_Trips_2017_Q3.csv",
        DATA_RAW / "Divvy_Trips_2017_Q4.csv",
    ],
    stations_path=DATA_RAW / "Divvy_Stations_2017_Q3Q4 (2).csv",
    save_demand_to=DATA_PROCESSED / "divvy_hourly_demand_weather.csv",
)
demand.head()

Saved demand dataset: /Users/martynaharasym/Desktop/DSB/Personal_project/bike-sharing-rebalancing/data/processed/divvy_hourly_demand_weather.csv

,station_id,hour,departures,arrivals,net_demand,temp,tmin,tmax,rhum,prcp,snwd,wspd,pres
0,66,2017-01-01 00:00:00,0,0,0,-1.1,-6.2,4.9,65,0.0,0,8.7,1020.4
1,66,2017-01-01 01:00:00,0,0,0,-1.1,-6.2,4.9,65,0.0,0,8.7,1020.4
2,66,2017-01-01 02:00:00,0,0,0,-1.1,-6.2,4.9,65,0.0,0,8.7,1020.4
3,66,2017-01-01 03:00:00,0,0,0,-1.1,-6.2,4.9,65,0.0,0,8.7,1020.4
4,66,2017-01-01 04:00:00,0,0,0,-1.1,-6.2,4.9,65,0.0,0,8.7,1020.4

In [ ]:
demand_model = add_time_and_lag_features(
    demand,
    lags=(1, 24, 168),
    drop_na_lags=True
)

demand_model.head()

,station_id,hour,departures,arrivals,net_demand,temp,tmin,tmax,rhum,prcp,...,dow_sin,dow_cos,month_sin,month_cos,dep_lag_1,arr_lag_1,dep_lag_24,arr_lag_24,dep_lag_168,arr_lag_168
168,2,2017-01-08 00:00:00,0,0,0,-11.5,-15.8,-6.8,50,0.0,...,-0.781831,0.62349,0.5,0.866025,0.0,1.0,0.0,0.0,0.0,0.0
169,2,2017-01-08 01:00:00,0,0,0,-11.5,-15.8,-6.8,50,0.0,...,-0.781831,0.62349,0.5,0.866025,0.0,0.0,0.0,0.0,0.0,0.0
170,2,2017-01-08 02:00:00,0,0,0,-11.5,-15.8,-6.8,50,0.0,...,-0.781831,0.62349,0.5,0.866025,0.0,0.0,0.0,0.0,0.0,0.0
171,2,2017-01-08 03:00:00,0,0,0,-11.5,-15.8,-6.8,50,0.0,...,-0.781831,0.62349,0.5,0.866025,0.0,0.0,0.0,0.0,0.0,0.0
172,2,2017-01-08 04:00:00,0,0,0,-11.5,-15.8,-6.8,50,0.0,...,-0.781831,0.62349,0.5,0.866025,0.0,0.0,0.0,0.0,0.0,0.0